Update prp to handle mykrobe csv format
Clinical-Genomics-Lund/bonsai-prp pull request #13
Opened 2023-12-27 16:27 UTC by ryanjameskennedy

2024-01-02 11:05 UTC, mhkc requested changes
The Mykrobe parser seems to be parsing resistance variants as resistance genes.

For instance is `katG_S315T` from the test output file is being parsed as a gene and not a variant.

2024-01-02 13:04 UTC, ryanjameskennedy commented
> The Mykrobe parser seems to be parsing resistance variants as resistance genes.
> 
> For instance is `katG_S315T` from the test output file is being parsed as a gene and not a variant.

`katG` is the gene the the variant is on? Or should I remove this entirely?

2024-01-02 14:04 UTC, mhkc commented
Yes, `katG` is the gene name where the mutation is located

2024-01-02 21:08 UTC, ryanjameskennedy commented
> Yes, `katG` is the gene name where the mutation was found.
> 
> Mykrobe report variants with the following format
> 
> > The variants column contains entries usually in the format _-:::. For example, rpsL_K43R-AAG781686AGG:0:513:3132 means K to R amino acid change at position 43 in the rpsL gene, which is AGG to AAG at position 781686 in the genome, with 0 reads supporting the reference, 513 depth on the alternative allele, and a genotype confidence of 3132.
> 
> https://github.com/Mykrobe-tools/mykrobe/wiki/AMR-prediction-output

No I understand that, just wondering if you mean that I must only report a variant in mykrobe's case?

2024-01-02 22:19 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        genes=_parse_mykrobe_amr_genes(prediction),
Should we use a default resistance gene format here or? Mykrobe doesn't detect amr genes per se, technically variants within these genes, right?

2024-01-03 11:35 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +            genes=[element_type["variants"].split("_")[0]],
Not sure why this is a list when it can only be one variant per gene? @mhkc

2024-01-03 13:14 UTC, mhkc requested changes

2024-01-03 13:36 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        try:
I think the try is not needed anyways because of this:
```
if element_type["variants"] is None:
            continue
```
Which says the same thing...

2024-01-03 13:44 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        _, ref_nt, alt_nt, position = get_mutation_type(var_info)
Doesn't do the same thing. This checks if changes are deletions or insertions based on the size of the ref nucleotides vs alt nucleotides. Not all variants are substitutions from mykrobe.

2024-01-03 13:49 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        variant = ResistanceVariant(
In the case of substitutions (not deletions and insertions which there are a lot of) I can do that but then we need to create our own AA translation table.

2024-01-03 13:51 UTC, ryanjameskennedy commented on prp/parse/typing.py
> +        if not lineage["susceptibility"].upper() == "R":
Yeah the csv row is empty if it's not `=="R"`

2024-01-03 15:05 UTC, mhkc commented on prp/parse/typing.py
> +        if not lineage["susceptibility"].upper() == "R":
ok.

2024-01-03 15:07 UTC, mhkc commented on prp/parse/phenotype/mykrobe.py
> +        variant = ResistanceVariant(
Could use the one included in Biopython

2024-01-03 15:35 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        _, ref_nt, alt_nt, position = get_mutation_type(var_info)
Well we don't have the whole aa/nt chain for the respective gene so we don't know what reading frame we're in (i.e. -3, -2, -1, +1, +2, +3)

2024-01-03 15:35 UTC, ryanjameskennedy commented on prp/parse/phenotype/mykrobe.py
> +        variant = ResistanceVariant(
Figured it out as you may see

2024-01-04 08:13 UTC, mhkc requested changes
Its getting closer.

The parser cant handle when there are multiple variants yielding the same resistance. For instance Rifampicin resistance in the test file,

mykrobe report that it is caused by three deletions,
 - `rpoB_TCATGGA1298T-TCATGGA761104T:152:2108:14397`
 - `rpoB_TTCATGGA1297TT-TTCATGGA761103TT:303:1978:13279`
 - `rpoB_CTGAGCCAATTCATGGACCAGAACAACCC1288CTGAGCCAATTCCAGAACAACCC-CTGAGCCAATTCATGGACCAGAACAACCC761094CTGAGCCAATTCCAGAACAACCC:1:2505:16677`

The current iteration of the parser only reports one variant

```
{'alt_aa': None,
 'alt_nt': 'T',
 'annotation': None,
 'ass_end_pos': None,
 'ass_start_pos': None,
 'change': 'TCATGGA1298T',
 'close_seq_name': None,
 'contig_id': None,
 'depth': 16677.0,
 'drugs': ['rifampicin'],
 'element_subtype': None,
 'element_type': 'AMR',
 'gene_symbol': 'rpoB',
 'method': 'kmer_count',
 'nucleotide_change': 'c.TCATGGA761104T',
 'phenotypes': [],
 'position': 761104,
 'protein_change': 'p.TCATGGA1298T',
 'ref_aa': None,
 'ref_database': None,
 'ref_id': None,
 'ref_nt': 'TCATGGA',
 'res_class': None,
 'res_subclass': None,
 'sequence_name': None,
 'strand': None,
 'target_length': None,
 'type': None,
 'variant_type': 'deletion'}
```

2024-01-04 08:13 UTC, mhkc commented on prp/parse/phenotype/mykrobe.py
> +        _, ref_nt, alt_nt, position = get_mutation_type(var_info)
good point

2024-01-04 10:51 UTC, ryanjameskennedy commented
> Its getting closer.
> 
> The parser cant handle when there are multiple variants yielding the same resistance. For instance Rifampicin resistance in the test file,
> 
> mykrobe report that it is caused by three deletions,
> 
> * `rpoB_TCATGGA1298T-TCATGGA761104T:152:2108:14397`
> * `rpoB_TTCATGGA1297TT-TTCATGGA761103TT:303:1978:13279`
> * `rpoB_CTGAGCCAATTCATGGACCAGAACAACCC1288CTGAGCCAATTCCAGAACAACCC-CTGAGCCAATTCATGGACCAGAACAACCC761094CTGAGCCAATTCCAGAACAACCC:1:2505:16677`
> 
> The current iteration of the parser only reports one variant
> 
> ```
> {'alt_aa': None,
>  'alt_nt': 'T',
>  'annotation': None,
>  'ass_end_pos': None,
>  'ass_start_pos': None,
>  'change': 'TCATGGA1298T',
>  'close_seq_name': None,
>  'contig_id': None,
>  'depth': 16677.0,
>  'drugs': ['rifampicin'],
>  'element_subtype': None,
>  'element_type': 'AMR',
>  'gene_symbol': 'rpoB',
>  'method': 'kmer_count',
>  'nucleotide_change': 'c.TCATGGA761104T',
>  'phenotypes': [],
>  'position': 761104,
>  'protein_change': 'p.TCATGGA1298T',
>  'ref_aa': None,
>  'ref_database': None,
>  'ref_id': None,
>  'ref_nt': 'TCATGGA',
>  'res_class': None,
>  'res_subclass': None,
>  'sequence_name': None,
>  'strand': None,
>  'target_length': None,
>  'type': None,
>  'variant_type': 'deletion'}
> ```

Solved!

2024-01-04 12:59 UTC, mhkc approved these changes
Looks good! Well done!

2024-01-04 13:00 UTC, merged