Add postalignqc subarg
Clinical-Genomics-Lund/bonsai-prp pull request #34
Opened 2024-01-30 19:00 UTC by ryanjameskennedy

2024-02-01 10:56 UTC, mhkc approved these changes
Looks good. A few comments but nothing major

2024-02-01 10:56 UTC, mhkc commented on Dockerfile
> +RUN apt update &&\
Consider using a multi stage build for binaries that are compiled, https://docs.docker.com/build/building/multi-stage/

2024-02-01 10:56 UTC, mhkc commented on Dockerfile
> +    apt-get install -y gcc make wget xz-utils git &&\
clean up the apt cache by removing `/var/lib/apt/lists` it reduces the image size

2024-02-01 10:56 UTC, mhkc commented on Dockerfile
> +    tar -xvf samtools-1.19.2.tar.bz2 &&\
remove build files to reduce image size

2024-02-01 10:56 UTC, mhkc commented on prp/parse/qc.py
> +    def parse_basecov_bed(self, basecov_fpath, thresholds):
I think this function could be simplified with Pandas or numpy because you are working with tabular data

2024-02-01 10:56 UTC, mhkc commented on prp/parse/qc.py
> +            iqr_median = "9999"
Why are you defining the default iqr_median to a 9999 string?

2024-02-01 10:56 UTC, mhkc commented on prp/parse/qc.py
> +        LOG.info(f"RUNNING: {' '.join(cmd)}")
Use `%s` substitutions instead of f-strings for logging. Eg ` LOG.info("RUNNING: %s", ' '.join(cmd))`

2024-02-01 10:56 UTC, mhkc commented on prp/parse/qc.py
> +            if not os.path.isfile(f"{self.bed}.interval_list"):
Please add some comments on what the script is doing

2024-02-01 11:20 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +        LOG.info(f"RUNNING: {' '.join(cmd)}")
May I ask why?

2024-02-01 12:14 UTC, ryanjameskennedy commented on Dockerfile
> +RUN apt update &&\
Did you mean something like this?

2024-02-01 12:17 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +            iqr_median = "9999"
That's what it's set to in [`postaln_qc.pl`](https://github.com/genomic-medicine-sweden/jasen/blob/307e900afd3fc598e5fc91c1078e48b5d5b5fb17/bin/postaln_qc.pl#L172)

2024-02-01 13:42 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +    def parse_basecov_bed(self, basecov_fpath, thresholds):
Still need to do this...

2024-02-01 14:15 UTC, mhkc approved these changes
Looks good

2024-02-02 08:55 UTC, alkc requested changes

2024-02-02 08:55 UTC, alkc commented on Dockerfile
> +WORKDIR /usr/src/app
Good job. Nice w/ a two step build.

2024-02-02 08:55 UTC, alkc commented on prp/parse/qc.py
> +        LOG.info(f"RUNNING: {' '.join(cmd)}")
Standard/recommended practice when passing strings to loggers. If you have an f-string, like so:

```
logging.debug(f"{my_var}")
```

that `my_var` will always be evaluated, even if your logging level is set to `INFO`

However if you put it as an arg/keyword:

```
logging.debug("%s", my_var)
```

evaluation of `my_var` will be deferred and only done if the logging statement is triggered.

If you think this will become a performance issue then switch to string substitutions.

2024-02-02 08:55 UTC, alkc commented on prp/parse/qc.py
> +        PostAlignQc: list of key-value pairs
Type annotation says it returns a `QcMethodIndex`

2024-02-02 08:55 UTC, alkc commented on prp/parse/qc.py
> +    def parse_hsmetrics(self, hsmetrics):
Needs a docstrng

2024-02-02 08:55 UTC, alkc commented on prp/parse/qc.py
> +        is_paired = 1 if remainder else 0
wait, why not `True`/`False` here

you could just return a `bool(remainder)`:

```
Python 2.7.5 (default, Apr  2 2020, 13:16:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> bool(0)
False
>>> bool(4)
True
>>> bool(2)
True
>>> bool(1)
True
```

2024-02-02 08:55 UTC, alkc commented on prp/parse/qc.py
> +class QC:
Add type hints to this class, since other functions/classes in this package already use them.

2024-02-02 09:10 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +        is_paired = 1 if remainder else 0
Yeah good shout

2024-02-02 09:12 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +class QC:
What are type hints?

2024-02-02 09:33 UTC, alkc commented on prp/parse/qc.py
> +class QC:
The additional info provided on what type each function arg is and what the function returns.

Example:

https://github.com/Clinical-Genomics-Lund/bonsai-prp/blob/3160de149f3eec103bc0e14db398e2beed7e6611/prp/parse/qc.py#L171

2024-02-05 13:40 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +        PostAlignQc: list of key-value pairs
Yeah It's a PostAlignQc within QcMethodIndex

2024-02-05 13:43 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +class QC:
What happens if they don't return anything?

2024-02-05 13:46 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +                    self.results['ins_size'] = vals[5]
I'm not sure of what we're extracting is correct, here is the tab-separated line of what this extracts:
```
MEDIAN_INSERT_SIZE	MODE_INSERT_SIZE	MEDIAN_ABSOLUTE_DEVIATION	MIN_INSERT_SIZE	MAX_INSERT_SIZE	MEAN_INSERT_SIZE	STANDARD_DEVIATION	READ_PAIRS	PAIR_ORIENTATION	WIDTH_OF_10_PERCENT	WIDTH_OF_20_PERCENT	WIDTH_OF_30_PERCENT	WIDTH_OF_40_PERCENT	WIDTH_OF_50_PERCENT	WIDTH_OF_60_PERCENT	WIDTH_OF_70_PERCENT	WIDTH_OF_80_PERCENT	WIDTH_OF_90_PERCENT	WIDTH_OF_95_PERCENT	WIDTH_OF_99_PERCENT	SAMPLE	LIBRARY	READ_GROUP
```

2024-02-05 14:30 UTC, alkc commented on prp/parse/qc.py
> +class QC:
`def foo() -> None:´

for multiple types of returned vals you can use `-> str | None`

2024-02-06 07:54 UTC, alkc commented on prp/parse/qc.py
> +                    self.results['ins_size'] = vals[5]
Dunno. Do you have any quality docs that might provide a reference?

2024-02-06 08:26 UTC, alkc reviewed
Looks good

Added some more suggestions

2024-02-06 08:26 UTC, alkc commented on prp/parse/qc.py
> +        line = subprocess.check_output(f"samtools view {self.bam} | head -n 1| awk '{{print $2}}'", shell=True, text=True)
If it works then it works but I'm thinking: Instead of relying on a subprocess/shell call, why not use something like `pysam` to do the same thing?

```
bam_file = pysam.AlignmentFile(self.bam)
for read in bam_file:
    return(read.is_paired())
```

2024-02-06 08:26 UTC, alkc commented on prp/parse/qc.py
> +        """Execute subproces"""
```suggestion
        """Execute subprocess"""
```

Typo

2024-02-06 08:26 UTC, alkc commented on prp/parse/qc.py
> +    """
```suggestion
    """
```

You can remove this, as it's already spelled out above.

2024-02-06 08:26 UTC, alkc commented on prp/parse/qc.py
> +def parse_alignment_results(sample_id: str, bam: File, reference: File, cpus: int, output: File, bed: File = None, baits: File = None) -> None:
```suggestion
def parse_alignment_results(sample_id: str, bam: File, reference: File, cpus: int, output: File, bed: File | None = None, baits: File | None = None) -> None:
```

2024-02-06 08:27 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +                    self.results['fold_80'] = vals[33]
Great idea!

2024-02-06 08:32 UTC, mhkc commented on prp/parse/qc.py
> +                    self.results['ins_size'] = vals[5]
If i were you I would break out the parsing functions from the class and test them individually using pytest. That makes it easier to debug them without having to run the script or monkeypatching the QC class.

2024-02-06 09:03 UTC, ryanjameskennedy commented on prp/parse/qc.py
> +        line = subprocess.check_output(f"samtools view {self.bam} | head -n 1| awk '{{print $2}}'", shell=True, text=True)
I tried to test this and got the following:
```
>>> print(seq_read)
M04035:24:000000000-CJPY8:1:1115:14075:19672    163     #0      1       60      34S144M #0      1       144     ACAAAATCCTTTTTATAACGCAAGTTCATTTTATACTACTGCTCAATTTTTTTACTTTTATCGATTAAAGATAGAAATACACGATGCGAGCAATCAAATTTCATAACATCACCATGAGTTTGGTCCGAAGCATGAGTGTTTACAATGTTTGAATACCTTATACAGTTCTTATACATAC      array('B', [34, 34, 34, 34, 34, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 36, 38, 38, 38, 38, 38, 38, 38, 38, 32, 38, 38, 38, 32, 36, 38, 38, 38, 38, 38, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 36, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37, 36, 38, 38, 38, 38, 38, 38, 34, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37, 37, 37, 31, 38, 38, 38, 38, 38, 33, 37, 38, 38, 38, 38, 38, 37, 38, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 36, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 35, 37, 38, 38, 38, 37, 37, 38, 38, 38, 38, 32, 37, 38, 38, 38, 38, 38, 37, 38, 38, 37, 38, 38, 38, 38, 38, 36, 37, 38, 38, 38, 38, 38, 38, 38, 34, 37, 37, 38, 38, 38, 38, 38, 38, 38, 34, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38])    [('NM', 2), ('MD', '115C3C24'), ('MC', '34S144M'), ('AS', 134), ('XS', 0)]
>>> print(seq_read.is_paired())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bool' object is not callable
```

2024-02-06 09:05 UTC, alkc commented on prp/parse/qc.py
> +        line = subprocess.check_output(f"samtools view {self.bam} | head -n 1| awk '{{print $2}}'", shell=True, text=True)
my bad!

2024-02-06 11:28 UTC, merged