36 add serotypefinder results parser
Clinical-Genomics-Lund/bonsai-prp pull request #37
Opened 2024-02-15 16:35 UTC by ryanjameskennedy

prp has been tested on ecoli samples

2024-02-16 15:04 UTC, mhkc requested changes
Code wise it looks good but I had some questions on how the information should be formatted.

2024-02-16 15:04 UTC, mhkc commented on prp/models/phenotype.py
> +    POINT = "POINT"
Is this a SNV?

2024-02-16 15:04 UTC, mhkc commented on prp/models/phenotype.py
> +    genes: List[Union[AmrFinderResistanceGene, AmrFinderGene, ResfinderGene, VirulenceGene, SerotypeGene]]
Should this be described as a phenotypic result isnt this for typing?

2024-02-16 16:11 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    POINT = "POINT"
This is the way it's reported in amrfinderplus. We're using their nomenclature right?

2024-02-16 16:16 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    genes: List[Union[AmrFinderResistanceGene, AmrFinderGene, ResfinderGene, VirulenceGene, SerotypeGene]]
Yeah but typing is still technically a phenotype. VirulenceGene is used for `stx` typing but it's in the `typing.py` model. I just copied that logic...

2024-02-16 17:10 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    depth: Optional[float] = Field(
Should I remove this `depth`variable as serotypefinder doesn't produce this in the output (same with virulencefinder yet it's included in `VirulenceGene`)? @mhkc

2024-02-20 08:14 UTC, mhkc approved these changes

2024-02-20 08:14 UTC, mhkc commented on prp/models/phenotype.py
> +    genes: List[Union[AmrFinderResistanceGene, AmrFinderGene, ResfinderGene, VirulenceGene, SerotypeGene]]
Yes but its used for tryping. Depending if we categorize a method as a phenotype prediction or typing method determines where and how its going to be displayed in bonsai.

2024-02-20 11:51 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    POINT = "POINT"
It's still element_type="AMR" & element_subtype = "POINT"

2024-02-20 12:11 UTC, merged