Add emmtyper, update shigapass and fix quast
Clinical-Genomics-Lund/bonsai-prp pull request #92
Opened 2024-10-07 14:35 UTC by ryanjameskennedy

2024-10-08 09:14 UTC, mhkc requested changes
Als the tests are failing.

2024-10-08 09:14 UTC, mhkc commented on prp/parse/typing.py
> +        gene = TypingResultGeneAllele(**emm_gene.model_dump())
Why are you recasting this object here when the fuction returns `EmmtypeGene`

2024-10-08 09:14 UTC, mhkc commented on prp/parse/phenotype/emmtyper.py
> +        element_subtype=subtype,
How do emm work? Are some not virulence genes?

2024-10-08 09:14 UTC, mhkc commented on prp/models/phenotype.py
> +    emm_like_alleles: list[str] = None
Either the type hint or the default is wrong

2024-10-08 09:14 UTC, mhkc commented on prp/models/phenotype.py
> +class EmmtypeGene(GeneBase):
How come that all fields are optional? Can there be completely empty records?

2024-10-08 09:14 UTC, mhkc commented on prp/models/phenotype.py
> +    ]] = Field(default=None, description="Further functional categorization of the genes.")
Are the categorisation not working? Are there times when it should be null?

2024-10-08 11:37 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    ]] = Field(default=None, description="Further functional categorization of the genes.")
If we don't separate `MethodIndex`'s. Will be solved when I revert changes.

2024-10-08 11:52 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    emm_like_alleles: list[str] = None
Well if there isn't an emm gene then it could be null?

2024-10-08 11:54 UTC, ryanjameskennedy commented on prp/models/phenotype.py
> +    emm_like_alleles: list[str] = None
Or are you saying it should be:
```
int | None = None
```
Instead of:
```
Optional[int] = None
```

2024-10-08 12:12 UTC, ryanjameskennedy commented on prp/models/typing.py
> -    rfb: Optional[str] = None
Here they are `Optional` as well though @mhkc

2024-10-08 14:43 UTC, ryanjameskennedy commented on prp/parse/phenotype/emmtyper.py
> +        element_subtype=subtype,
Emm encodes the M virulence protein found on the cell surface. Should we call the `emmtype` the `element_subtype` instead?

2024-10-08 14:44 UTC, ryanjameskennedy commented on prp/parse/typing.py
> +def parse_emmtyper_pred(path: str) -> MethodIndex | None:
No I guess not, clearly copied `parse_serotypefinder_oh_typing`

2024-10-08 14:46 UTC, ryanjameskennedy commented on prp/parse/typing.py
> +        gene = TypingResultGeneAllele(**emm_gene.model_dump())
You've done that in `parse_serotypefinder_oh_typing` and `parse_virulencefinder_stx_typing`, I was just keeping the structure...

2024-10-09 07:31 UTC, ryanjameskennedy commented on prp/parse/typing.py
> +        gene = TypingResultGeneAllele(**emm_gene.model_dump())
Not really relevant with the reversion...

2024-10-09 14:32 UTC, mhkc commented on prp/parse/phenotype/emmtyper.py
> +        element_subtype=subtype,
Good question. I dont know. What do you think would be the most explainatory?

We could introduce an "other" category, similar to null but then its easiery to query

2024-10-09 17:08 UTC, ryanjameskennedy commented on prp/parse/phenotype/emmtyper.py
> +        element_subtype=subtype,
We usually use `element_subtype` for these sorts of things...

2024-10-10 13:06 UTC, merged